name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: "sudo apt update -y && sudo apt install -y pkg-config libx11-dev cmake libglib2.0-dev"

      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check --all
